# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

norm2 <- function(x) {
    .Call(`_bigtime_norm2`, x)
}

prox2HVAR <- function(v, lambda, k, p) {
    .Call(`_bigtime_prox2HVAR`, v, lambda, k, p)
}

FistaElem <- function(Y, Z, phi, p, k, lambda, eps, tk) {
    .Call(`_bigtime_FistaElem`, Y, Z, phi, p, k, lambda, eps, tk)
}

gamloopElem <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p) {
    .Call(`_bigtime_gamloopElem`, beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p)
}

ST1a <- function(z, gam) {
    .Call(`_bigtime_ST1a`, z, gam)
}

ST3a <- function(z, gam) {
    .Call(`_bigtime_ST3a`, z, gam)
}

gamloopFista <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s) {
    .Call(`_bigtime_gamloopFista`, beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s)
}

gamloopElem2 <- function(bcube, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, flag_restart_opt = 1L) {
    .Call(`_bigtime_gamloopElem2`, bcube, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, flag_restart_opt)
}

gamloopFista2 <- function(bcube, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk) {
    .Call(`_bigtime_gamloopFista2`, bcube, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk)
}

lassoVARFistcpp <- function(beta, trainY, trainZ, lambda, tol, p) {
    .Call(`_bigtime_lassoVARFistcpp`, beta, trainY, trainZ, lambda, tol, p)
}

HVARElemAlgcpp <- function(beta, trainY, trainZ, lambda, tol, p, flag_restart_opt = 0L) {
    .Call(`_bigtime_HVARElemAlgcpp`, beta, trainY, trainZ, lambda, tol, p, flag_restart_opt)
}

HVAR_cvaux_loop_cpp <- function(Y, Z, tseq, gamm, eps, p, estim) {
    .Call(`_bigtime_HVAR_cvaux_loop_cpp`, Y, Z, tseq, gamm, eps, p, estim)
}

HVARX_NEW_export_cpp <- function(fullY, fullZ, fullX, k, kX, p, s, lambdaPhi, lambdaB, eps, max_iter, alpha, type, Binit, Phiinit) {
    .Call(`_bigtime_HVARX_NEW_export_cpp`, fullY, fullZ, fullX, k, kX, p, s, lambdaPhi, lambdaB, eps, max_iter, alpha, type, Binit, Phiinit)
}

HVARX_cvaux_cpp_loop <- function(Y, Z, X, lambdaPhiseq, lambdaBseq, eps, max_iter, k, kX, p, s, alpha, estim, tseq) {
    .Call(`_bigtime_HVARX_cvaux_cpp_loop`, Y, Z, X, lambdaPhiseq, lambdaBseq, eps, max_iter, k, kX, p, s, alpha, estim, tseq)
}

LGSearch_cpp <- function(gstart, Y, Z, beta, estim, k, p) {
    .Call(`_bigtime_LGSearch_cpp`, gstart, Y, Z, beta, estim, k, p)
}

