# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

norm2 <- function(x) {
    .Call(`_bigtime_norm2`, x)
}

prox2HVAR <- function(v, lambda, k, p) {
    .Call(`_bigtime_prox2HVAR`, v, lambda, k, p)
}

FistaElem <- function(Y, Z, phi, p, k, lambda, eps, tk) {
    .Call(`_bigtime_FistaElem`, Y, Z, phi, p, k, lambda, eps, tk)
}

gamloopElem <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p) {
    .Call(`_bigtime_gamloopElem`, beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p)
}

ST1a <- function(z, gam) {
    .Call(`_bigtime_ST1a`, z, gam)
}

ST3a <- function(z, gam) {
    .Call(`_bigtime_ST3a`, z, gam)
}

gamloopFista <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s) {
    .Call(`_bigtime_gamloopFista`, beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s)
}

